# Generated by Django 2.2.13 on 2020-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200807_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', through='webapp.ArticleTag', to='webapp.Tag', verbose_name='Теги'),
        ),
    ]
