# Generated by Django 2.2.13 on 2020-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200807_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
